sudo: required

services:
  - docker

before_install:
  - docker build -t calexa22/multi-docker-test-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true calexa22/multi-docker-test-dev yarn test

after_success:
  - docker build -t calexa22/multi-docker-test-client ./client
  - docker build -t calexa22/multi-docker-test-proxy ./proxy
  - docker build -t calexa22/multi-docker-test-server ./server
  - docker build -t calexa22/multi-docker-test-worker ./worker

  # Log in to Docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID"  --password-stdin

  # Push images to Docker Hub
  - docker push calexa22/multi-docker-test-client
  - docker push calexa22/multi-docker-test-proxy
  - docker push calexa22/multi-docker-test-server
  - docker push calexa22/multi-docker-test-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-test
  env: Multidockertest-env
  bucket_name: elasticbeanstalk-us-east-2-984595019613
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"